apiVersion: v1
kind: Service
metadata:
  name: train-schedule-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: train-schedule
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-dp
spec:
  selector:
    matchLabels:
      app: train-schedule
  replicas: 1
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule-apps
        image: reg.foobz.com.au/foobz/train-schedule-sc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
